dist: xenial
language: python
python: 3.6
install:
  - pip install -r requirements.txt
  - pip install pylint
script:
  - pip install -e .
  - pylint pdftitle.py
  - bash test.sh
  - bash test_max2.sh
  - bash test_eliot.sh
  - bash testc.sh
