version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            pip install pylint
      - run:
          command: |
            pip install -e .
            make test
